name: Run R Script Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour on the hour

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
    
    - name: Install dependencies
      run: |
        R -e 'install.packages(c("tidyverse", "janitor", "lubridate", "rvest"))'
    
    - name: Run R script
      run: Rscript idalia/power_outages.Rmd
